name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm run test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with: 
         push: true
         tags: kauaqt/api-teste:v1
    
      - name: Build docker image
        run: docker build -t kauaqt/api-teste:v1 .

      - name: Push image
        run: docker push kauaqt/api-teste:v1
